steps:
  # Step 1: Build the Docker image
#  - name: gcr.io/cloud-builders/docker
#    args:
#      - build
#      - '-t'
#      - '$_SERVICE_NAME:$COMMIT_SHA'
#      - '.'

  # Step 2: Log in to Docker using secrets
  - name: gcr.io/cloud-builders/docker
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        docker build -t "$_SERVICE_NAME:$COMMIT_SHA" .
        docker push "$_SERVICE_NAME:$COMMIT_SHA"


 # Step 3: Push the Docker image to GCR
 # - name: gcr.io/cloud-builders/docker
 #   args:
 #     - push
 #     - '$_SERVICE_NAME:$COMMIT_SHA'

  # Step 4: Deploy the application to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - '--image'
      - '$_SERVICE_NAME:$COMMIT_SHA'
      - '--region'
      - $_DEPLOY_REGION
    entrypoint: gcloud
options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1200s

images:
  - '$_SERVICE_NAME:$COMMIT_SHA'
