steps:
  # Step 0: Set up secrets for testing
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'test']
    secretEnv: ['GOOGLE_APPLICATION_CREDENTIALS']
  # Step 1: Build the Docker image with the test results
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'europe-west1-docker.pkg.dev/trustisend-433213/trustisend-gcr/dev:$COMMIT_SHA'
      - '.'

  # Step 2: Push the Docker image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'europe-west1-docker.pkg.dev/trustisend-433213/trustisend-gcr/dev:$COMMIT_SHA'

  # Step 3: Deploy the application to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: 'gcloud'
    args:
      - run
      - deploy
      - dev  # Cloud Run service name
      - '--image'
      - 'europe-west1-docker.pkg.dev/trustisend-433213/trustisend-gcr/dev:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--quiet'
      - '--memory'
      - '2Gi'  # Set the memory limit to 2GiB
      - '--timeout'
      - '900s'  # Increase the timeout to 15 minutes
      # Mount Firestore and Cloud Storage secrets
      - '--update-secrets'
      - '/cred-mnt/cred=projects/579596661856/secrets/credentials:latest'

      # Set environment variable to point to the Firestore credentials secret
      - '--set-env-vars'
      - 'GOOGLE_APPLICATION_CREDENTIALS=/cred-mnt/cred'

images:
  - 'europe-west1-docker.pkg.dev/trustisend-433213/trustisend-gcr/dev:$COMMIT_SHA'

availableSecrets:
  secretManager:
    - versionName: projects/579596661856/secrets/credentials/versions/1
      env: 'GOOGLE_APPLICATION_CREDENTIALS'