steps:
  # Step 0: Build the Docker image and tag it with the commit SHA
- name: gcr.io/cloud-builders/docker
  entrypoint: /bin/bash
  args:
    - '-c'
    - |
      docker build -t europe-west1-docker.pkg.dev/trustisend-433213/trustisend-gcr/gc-storage:$COMMIT_SHA .
  secretEnv:
    - 'KEY'


  # Step 1: Push the Docker image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'europe-west1-docker.pkg.dev/trustisend-433213/trustisend-gcr/gc-storage:$COMMIT_SHA'

  # Step 2: Deploy the application to Cloud Run using the built image
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - run
      - deploy
      - gc-storage  # Cloud Run service name
      - '--image'
      - 'europe-west1-docker.pkg.dev/trustisend-433213/trustisend-gcr/gc-storage:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--quiet'
    entrypoint: gcloud

availableSecrets:
  secretManager:
    - versionName: projects/579596661856/secrets/gc-storage-key/versions/1
      env: 'KEY'

# Specify the images that will be pushed by Cloud Build
images:
  - 'europe-west1-docker.pkg.dev/trustisend-433213/trustisend-gcr/gc-storage:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1200s
