steps:
  # Étape 1: Compiler le projet avec Maven et exécuter les tests
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', 'test']
    dir: 'dev/test-login/social-login'  # Chemin vers le répertoire contenant le fichier pom.xml

  # Étape 2: Déployer sur Google App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
    dir: 'dev/test-login/social-login'  # Chemin vers le répertoire contenant le fichier app.yaml
options:
  logging: NONE