steps:
  # Step 1: Fetch the secret from Secret Manager and save it to a workspace file (shared across steps)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Fetching credentials from Secret Manager..."
        gcloud secrets versions access latest --secret="credentials" > /workspace/gcloud-credentials.json

  # Step 2: Use a Maven image with Java 21 to run the tests
  - name: 'maven:3.9.4-eclipse-temurin-21'  # Maven image with Java 21
    dir: '/workspace/app'  # Change to the /app directory
    env:
      - 'GOOGLE_APPLICATION_CREDENTIALS=/workspace/gcloud-credentials.json'  # Use the credentials from /workspace
    args: ['mvn', 'clean', 'test']

  # Step 3: Clean up the credentials file (optional but recommended)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Cleaning up credentials file..."
        rm /workspace/gcloud-credentials.json

  # Step 4: Build the Docker image after tests have passed
  - name: 'gcr.io/cloud-builders/docker'
    dir: '/workspace'  # Return to the /workspace directory
    args:
      - build
      - '-t'
      - 'europe-west1-docker.pkg.dev/trustisend-433213/trustisend-gcr/dev:$COMMIT_SHA'
      - '.'

  # Step 5: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'europe-west1-docker.pkg.dev/trustisend-433213/trustisend-gcr/dev:$COMMIT_SHA'

  # Step 6: Deploy the application to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - run
      - deploy
      - dev  # Cloud Run service name
      - '--image'
      - 'europe-west1-docker.pkg.dev/trustisend-433213/trustisend-gcr/dev:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--quiet'
      - '--memory'
      - '2Gi'  # Set the memory limit to 2GiB
      - '--timeout'
      - '900s'  # Increase the timeout to 15 minutes
      - '--update-secrets'
      - '/cred-mnt/cred=projects/579596661856/secrets/credentials:latest'
      - '--set-env-vars'
      - 'GOOGLE_APPLICATION_CREDENTIALS=/cred-mnt/cred'

options:
  logging: CLOUD_LOGGING_ONLY  # Use Cloud Logging only
timeout: 1200s
