steps:
  # Step 1: Build the Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - '$_SERVICE_NAME:$COMMIT_SHA'
      - '.'

  # Step 2: Push the Docker image to the (GCR)
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_SERVICE_NAME:$COMMIT_SHA'

  # Step 3: Deploy the application to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - '--image'
      - '$_SERVICE_NAME:$COMMIT_SHA'
      - '--region'
      - $_DEPLOY_REGION
      - '--platform'
      - $_PLATFORM
    entrypoint: gcloud
options:
    logging: CLOUD_LOGGING_ONLY
timeout: 1200s

images:
  - '$_SERVICE_NAME:$COMMIT_SHA'
