steps:
  # Step 1: Build the Docker image
#  - name: gcr.io/cloud-builders/docker
#    args:
#      - build
#      - '-t'
#      - '$_SERVICE_NAME:$COMMIT_SHA'
#      - '.'

  # Step 2: Log in to Docker using secrets
  - name: gcr.io/cloud-builders/docker
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        echo "Logging into Docker with username: $$USERNAME"
        echo "$$PASSWORD" | docker login -u $$USERNAME --password-stdin
        docker build -t "$_SERVICE_NAME:$COMMIT_SHA" .
        docker push "$_SERVICE_NAME:$COMMIT_SHA"
    secretEnv:
      - 'USERNAME'
      - 'PASSWORD'


 # Step 3: Push the Docker image to GCR
 # - name: gcr.io/cloud-builders/docker
 #   args:
 #     - push
 #     - '$_SERVICE_NAME:$COMMIT_SHA'

  # Step 4: Deploy the application to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - '--image'
      - '$_SERVICE_NAME:$COMMIT_SHA'
      - '--region'
      - $_DEPLOY_REGION
      - '--platform'
      - $_PLATFORM
    entrypoint: gcloud

availableSecrets:
  secretManager:
    - versionName: projects/$_PROJECT_ID/secrets/docker-username/versions/1
      env: 'USERNAME'
    - versionName: projects/$_PROJECT_ID/secrets/docker-password/versions/1
      env: 'PASSWORD'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1200s

images:
  - '$_SERVICE_NAME:$COMMIT_SHA'
