services:
  web:
    build: ./projects/spring-boot
    ports:
      - "8080:8080"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/keys/google-credentials.json
  av:
    build: ./projects/av
    ports:
      - "8081:8080"
  schedule:
    build: ./projects/schedule
    ports:
      - "8082:8080"